authorName: hs
experimentName: mixer_arxiv_branch_tuning
trialConcurrency: 4
maxExecDuration: 24h
maxTrialNum: 200
#choice: local, remote, pai
trainingServicePlatform: local
searchSpacePath: search_space.json
#choice: true, false
# if use annotation, do need to change the code
useAnnotation: false
tuner:
  #choice: TPE, Random, Anneal, Evolution, BatchTuner, MetisTuner, GPTuner
  #SMAC (SMAC should be installed through nnictl)
  builtinTunerName: Evolution
  classArgs:
    #choice: maximize, minimize
    optimize_mode: maximize
trial:
  command: cd ../;  CUDA_VISILE_DEVICES=0,3 python tmp_nni_batch_arxiv_rw.py  --epochs=1000  --batch_size=80000  
  codeDir: .
  gpuNum: 2
localConfig:
  useActiveGpu: true
  maxTrialNumPerGpu: 3

# trainingService:
#   platform: local
#   useActiveGpu: True